version: '3.4'

services:
  simpleconsoleapp:
    image: simpleconsoleapp
    build:
      context: .
      dockerfile: KubernetesExamples/SimpleConsoleApp/Dockerfile
    volumes:
      - C:\k8-data\:/app/data  #/Users/jt/k8-data/

  configmapconsoleapp:
    image: configmapconsoleapp
    build:
      context: .
      dockerfile: KubernetesExamples/ConfigMapConsoleApp/Dockerfile

