apiVersion: batch/v1
kind: CronJob
metadata:
  name: consoleapp1-cronjob
  namespace: my-local-namespace
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: simpleconsoleapp
            image: simpleconsoleapp:latest
            imagePullPolicy: Never
            ports:
              # Add your container ports if needed
            volumeMounts:
            - name: my-volume
              mountPath: /app/data/
            env:
            - name: POD_NAME  
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  
          volumes:
          - name: my-volume
            persistentVolumeClaim:
              claimName: my-persistent-volume-claim 
