apiVersion: batch/v1
kind: Job
metadata:
  name: secretsconsoleapp-job  
  namespace: my-local-namespace-secrets
spec:
  completions: 1  
  parallelism: 1
  template:
    metadata:
      labels:
        app: secretsconsoleapp
    spec:
      serviceAccountName: default 
      restartPolicy: Never
      containers:
      - name: secretsconsoleapp
        image: secretsconsoleapp:latest
        imagePullPolicy: Never
        ports:
          # Add your container ports if needed
        env:
        - name: JOB_NAME  
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  
        - name: JOB_NAMESPACE  
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JOB_SECRET 
          value: my-secret
