apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-binding
  namespace: my-local-namespace-secrets
subjects:
- kind: ServiceAccount
  name: default 
  namespace: my-local-namespace-secrets
roleRef:
  kind: Role
  name: secrets-reader-role  
  apiGroup: rbac.authorization.k8s.io
