apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmap-reader-role
  namespace: my-local-namespace-configmap  
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
